.Dd February 9, 2021
.Dt HTCRYSTALBALL 1
.Os \" Current operating system.
.
.Sh NAME
.Nm htcrystalball (htcb)
.Nd calculate the runtime and maximum number of jobs that can run on an HTCondor pool
.
.Sh SYNOPSIS
.Nm
.Op Fl h
|
.Fl Fl cpu Ar num
.Fl Fl ram Ar size
.Op Fl g Ar num
.Op Fl d Ar size
.Op Fl j Ar num
.Op Fl t Ar time
.Op Fl m Ar num
.Op Fl v
.
.Sh DESCRIPTION
.Nm
calculates how many jobs (of a user\[hy]specified number and size) can run
on an HTCondor pool.
It also can estimate runtime (core hours and wall time) and node\[hy]specific
matching (aiding those with node\[hy]level licensing restrictions).
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.
.It Fl c | Fl Fl cpu Ar number
The number of CPU cores per job.
.
.It Fl r | Fl Fl ram Ar size
The amount of RAM per job, including a unit (e.g. 10G).
.
.It OPTIONS
.
.It Fl h | Fl Fl help
Prints a summary of
.Nm Ap s
command\[hy]line options and exits.
.
.It Fl g | Fl Fl gpu Ar number
The number of GPUs per job.
.
.It Fl d | Fl Fl disk Ar size
The disk space per job, including a unit (e.g. 50G).
.
.It Fl j | Fl Fl jobs Ar number
The number of jobs to be executed.
.
.It Fl t | Fl Fl time Ar time
The estimated time for one job to be executed.
.
.It Fl m | Fl Fl maxnodes Ar number
The maximum number of nodes jobs can be executed on.
Sometimes necessary due to software license restrictions.
.
.It Fl v | Fl Fl verbose
Prints a table listing each node, its resources, and proposed usage.
.El
.
.Sh EXIT STATUS
.Ex -std
.
.Sh EXAMPLES
Basic output:
.Dl htcrystalball \-\-cpu 1 \-\-ram 7500M \-\-jobs 1
.
Verbose:
.Dl htcrystalball \-\-cpu 1 \-\-ram 7500M \-\-jobs 1 \-\-verbose
.
Big job with runtime projection:
.Dl htcb \-\-cpu 16 \-\-ram 16G \-\-disk 100G \-\-jobs 20 \-\-time 5h
.
Limit to a maximum number of nodes:
.Dl htcb \-\-cpu 16 \-\-ram 16G \-\-disk 100G \-\-maxnodes 2 \-\-jobs 20 \-\-time 5h
.
GPU job:
.Dl htcb \-\-cpu 1 \-\-gpu 1 \-\-ram 8G \-\-disk 64G \-\-jobs 10 \-\-time 2h
.
.Sh SEE ALSO
The
.Nm
repository is available at
.Lk https://github.com/psyinfra/HTCrystalBall .
Bug reports, patches, and (constructive) input are always welcome.
.
.Sh AUTHORS
.Nm
was created by
.An Jona Marcus Fischer
.Mt j.fischer@fz\[hy]juelich.de .
.
.Sh COPYRIGHT
.Nm
is released under the
.Qq ISC License .
See the LICENSE file for more information.
