.Dd February 1, 2021
.Dt HTCRYSTALBALL 1
.Os \" Current operating system.
.
.Sh NAME
.Nm htcrystalball (htcb)
.Nd calculate how many of a specified job size can run on an HTCondor pool
.
.Sh SYNOPSIS
.Nm
.Op CPU
.Op RAM
.Ar ...
.Op OPTIONS
.
.Sh DESCRIPTION
.Nm
calculates how many jobs (of a user\[hy]specified number and size) can run
on an HTCondor pool.
It also can provide estimates of overall runtime and
node\[hy]specific matching (aiding those with node\[hy]level licensing
restrictions).
.Pp
Its arguments are as follows:
.Bl -tag -width Ds
.
.It Ar \-c | Ar \-\-cpu
The number of CPU cores.
.
.It Ar \-r | Ar \-\-ram
The amount of RAM, including a unit (e.g. 10G).
.
.It OPTIONS
.
.It Fl h | Fl Fl help
Prints a summary of
.Nm Ap s
command\[hy]line options and exits.
.
.It Fl g | Fl Fl gpu
The number of requested GPUs.
.
.It Fl d | Fl Fl disk
The disk space, including a unit (e.g. 50G).
.
.It Fl j | Fl Fl jobs
The number of jobs to be executed.
.
.It Fl t | Fl Fl time
The estimated time for one job to be executed.
.
.It Fl m | Fl Fl maxnodes
pass the maximum number of nodes for all jobs to be executed (due to Matlab licensing)
.
.It Fl v | Fl Fl verbose
print out a table for a slot config overview executable jobs
.El
.
.Sh EXIT STATUS
.Ex -std
.
.Sh EXAMPLES
Simple small job:
.Dl htcb \-\-cpu 1 \-\-ram 7500M \-\-jobs 1
.
Single-core with huge RAM:
.Dl htcb \-\-cpu 1 \-\-ram 128G \-\-disk 1T
.
Big multi-core with medium RAM:
.Dl htcb \-\-cpu 16 \-\-ram 16G \-\-disk 100G \-\-jobs 20 \-\-time 5h
.
max-nodes mode (a.k.a. Matlab mode):
.Dl htcb \-\-cpu 16 \-\-ram 16G \-\-disk 100G \-\-maxnodes 2 \-\-jobs 20 \-\-time 5h
.
GPU job:
.Dl htcb \-\-cpu 1 \-\-gpu 1 \-\-ram 8G \-\-disk 64G \-\-jobs 10 \-\-time 2h
.
.Sh SEE ALSO
The
.Nm
repository is available at
.Lk https://github.com/psyinfra/HTCrystalBall .
Bug reports, patches, and (constructive) input are always welcome.
.
.Sh AUTHORS
.Nm
was created by
.An Jona Marcus Fischer
.Mt j.fischer@fz\[hy]juelich.de .
.
.Sh COPYRIGHT
.Nm
is released under the
.Qq ISC License .
See the LICENSE file for more information.
