name: tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Set up environment
      uses: actions/checkout@v2
      with:  # no need for the history
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -y install mandoc
        pip install -U pip
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt
        python -m pip install --upgrade -r requirements-test.txt
        python -m pip install --upgrade codecov pytest-cov
        python -m pip list
    - name: Run tests
      run: |
        pytest --version && pytest --cov=htcrystalball/ --cov-report=xml
        python setup.py install
    - name: Run linters
      run: |
        pyflakes --version && pyflakes *.py
        mandoc -T lint man/man1/htcrystalball.1
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
